module.exports={
    images:{
        domains:[
            "links.papareact.com",
            "platform-lookaside.fbsbx.com",
            "firebasestorage.googleapis.com",
            "source.unsplash.com/random/40x40",
            "drive.google.com",
        ],
    },
};
